id = "random_bootlogo"

name = "Random Bootlogo"

# Runs after the main system is initialized, which is safer than "base".
after = ["init"]

# This is the key part: ensures the script runs on every single boot.
execution_policy = "Always"

# Tells the patcher which script file to execute.

compatible_versions = ["*"]
