#!/opt/bin/bash

DISK="$(ls /dev/sd[a-z] | xargs -i fdisk -l {} | grep -i fat | awk '{print $1}' | head -1)"
[[ ! -z "$DISK" ]] && mount -t vfat,exfat -o iocharset=utf8 $DISK /mnt/exUDISK && \
  echo "Successfully mounted /mnt/exUDISK" || \
  echo "Could not find valid FAT or exFAT USB stick, not mounted"

